version: '3.8'

volumes:
  postgres-data:

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile.devcontainer
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
