FROM mcr.microsoft.com/devcontainers/go:1.20-bookworm

# USER root
# RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl sudo tar
# RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-460.0.0-linux-x86_64.tar.gz
# RUN tar -xf google-cloud-cli-460.0.0-linux-x86_64.tar.gz
# RUN ./google-cloud-sdk/install.sh

# USER vscode
