apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-consumer
  template:
    metadata:
      labels:
        app: submission-consumer
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 30
      containers:
      - name: submission-consumer
        image: docker.io/wuttinanhi/codejudgesystem
        resources:
          limits:
            cpu: 2000m
            ephemeral-storage: 1Gi
            memory: 2048Mi
          requests:
            cpu: 2000m
            ephemeral-storage: 1Gi
            memory: 2048Mi
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: cjs-configmap
        env:
        - name: APP_MODE
          value: CONSUMER
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
